### ISSUE TITLE
Extensions support?

### ISSUE THREAD

**Issue by mrichman** [duckduckgo/macos-browser#3173]
I'd love to use this as my daily driver, but none of my favorite extensions are available. What's on the roadmap?

**Comment by samsymons** [comment]
Hey @mrichman! Thanks for opening this issue - extensions are on our roadmap, but we don't have any timeframe to share right now. I'll let you know here once we have something to announce. Thanks!

**Comment by meguroyama** [comment]
For the contributors reading this I'd request that as extensions would be nice. There are core features that should implemented with our without extensions support.

* Ad-Block
* Secure DNS (DoH)
* Dark mode support (dark reader)
* PDF edit support
* Either userstyles or userscripts support
