### ISSUE TITLE
Add feature to drag selected text to “+” icon to open a new tab with search results

### ISSUE THREAD

**Issue by d0sse** [duckduckgo/macos-browser#3189]
It would be great to have the ability to drag selected text to the “+” icon (new tab button) in the browser to automatically open a new tab with search results for the dragged text (like in safari and all other browsers) 

**Use Case:**

1. A user selects a piece of text on a webpage.
2. The user drags the selected text to the "+" icon.
3. A new tab opens with the search engine's results for the dragged text.

This feature would improve user experience by making it faster and more intuitive to search for selected text.

**Video example**

https://github.com/user-attachments/assets/324e2f65-3b9c-4e45-b2e6-daa60604dc04

**Comment by jotaemepereira** [comment]
This was implemented and released on https://github.com/duckduckgo/macos-browser/releases/tag/1.107.0. 

Thanks @d0sse for the feedback!
